### ISSUE TITLE
FIDO2

### ISSUE THREAD

**Issue by paulo-raca** [gl-sergei/u2f-token#17]
Hello, does this project support the newer FIDO2 standard?
How hard would it be to implement it?

Thanks!

**Comment by gl-sergei** [comment]
This project does not support FIDO2, neither it is planned. I consider implementing FIDO2 but for something like NRF52 with NFC and Bluetooth support.

**Comment by paulo-raca** [comment]
Very Nice! 

I've (also) been looking for an fido2 nfc tag that doesn't cost a fortune, this might be it :)
