### ISSUE TITLE
Update the token with USB

### ISSUE THREAD

**Issue by NewRedsquare** [gl-sergei/u2f-token#34]
I don't know if it's hard to do, but when i update the token , i need to connect many wires to my st dongle and that's quite hard to do everytime. So i thought it could be a good idea to make an "updater" like reGnual ( gnuk project ) [https://salsa.debian.org/gnuk-team/gnuk/gnuk/tree/master/regnual](url) and described as : 

> How to run the script: ::
> $ cd tool
>  $ ./upgrade_by_passwd.py ../regnual/regnual.bin ../src/build/gnuk.bin
> 
> Then, the script on your host PC invoke the steps described above, and
> you will get new version

**Comment by gl-sergei** [comment]
I would prefer to leave bootloader and software updates for other projects. There are some bootloaders available for STM32F103. https://mcuboot.com/ looks quite promising. Should you need to add new make target to support mcuboot (https://mcuboot.com/mcuboot/design.html) or any other bootloader, PRs are welcome!
